version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3055:3055"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: 12345678
      DB_NAME: nodejs
      DB_PORT: 3307
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: nodejs
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
  nginx:
    container_name: nginx
    restart: unless-stopped  # Sửa lỗi từ "estart" thành "restart"
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem
    depends_on:
      - app  # Chuyển depends_on vào trong service nginx

  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./redis.log:/var/log/redis/redis.log  # Sửa lỗi đường dẫn và định dạng cho file log

volumes:
  db-data:
  redis-data:
