version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3055:3055"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: 12345678
      DB_NAME: nodejs
      DB_PORT: 3307
      MAIL: huy343536@gmail.com
      MAIL_PASSWORD: swsa axux pgyc ljvy
      CLOUD_NAME: ecommercegroup
      CLOUDINARY_API_KEY: 772858273968731
      CLOUDINARY_API_SECRET: NdLAr1tYR9QDwlRZZB-LDJZXtvk
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: nodejs
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

  nginx:
    image: nginx:latest
    build:
      context: .
    volumes:
      - ./ssl:/ssl
      - ./be-ssl:/be-ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./redis.conf:/var/log/redis

volumes:
  db-data:
  redis-data:
