version: '3.8'

services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3055:3055"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: ${DB_PASS}  
      DB_NAME: nodejs
      DB_PORT: 3307  
      MAIL: ${MAIL}  
      MAIL_PASSWORD: ${MAIL_PASSWORD}  
      CLOUD_NAME: ecommercegroup
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}  
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}  
    depends_on:
      - db
      - redis
    networks:
      - mynetwork

  db:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}  
      MYSQL_DATABASE: nodejs
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    container_name: nginx
    build:
      context: .
    volumes:
      - ./ssl:/ssl
      - ./be-ssl:/be-ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - mynetwork

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - mynetwork
volumes:
  db-data:
networks:
  mynetwork:
