version: '3.8'
services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3055:3055"
    # networks:
    #   - app-tier 
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=12345678
      - DB_NAME=nodejs
      - DB_PORT=3307
    depends_on:
      - db
  db:
    image: mysql:8.1
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=nodejs
    ports:
      - "3307:3306"  
    # networks:
    #   - app-tier 
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: