openapi: 3.0.0
info:
  title: Ecommerce API
  description: API endpoints for Shop Ecommerce
  version: 1.0.0
servers:
  - url: "http://localhost:3055/"
    description: Server
paths:
  /v1/api/oauth/facebook-login:
    get:
      tags:
        - Oauth
      summary: Redirect to Facebook login
      responses:
        '302':
          description: Redirects to Facebook login page
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
      security:
        - oauth2: []

components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: "https://www.facebook.com/v12.0/dialog/oauth"
          tokenUrl: "https://graph.facebook.com/v12.0/oauth/EAAKYzbDVIMoBO6eKjS2pSak6wnLGgrB0eoPqeo63X4FK7Gs4YCZA4zZCuxfvrdrysU3nqszUHOQKp6QvoWv5e1Hx3zyTSiTZCofNvgxf3mr9RpTTag6aqniCZC9qA0EKrqWJH9bkZCxF9NVqqDcw1LJs4vlTJpzmyKAWw98p4K1VrfX53s28iYSaHfWebZBwOfmqJBOzqAucitLYqVsLQAIZBJhLPGjSw6g0uHYb05qXeZCzMaNDtKOh1G2rq2EOnQZDZD"
          # scopes:
          #   email: Access user's email address
          #   public_profile: Access user's public profile information